export { default as Intro } from './Intro'
export { default as Register } from './Register'
export { default as Signin } from './Signin'
export { default as Welcome } from './Welcome'
export { default as Main } from './Main'
